# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 93) do

  create_table "activity_limits", :force => true do |t|
    t.column "contributor_type", :string,   :null => false
    t.column "contributor_id",   :integer,  :null => false
    t.column "limit_feature",    :string,   :null => false
    t.column "limit_max",        :integer
    t.column "limit_frequency",  :integer
    t.column "current_count",    :integer,  :null => false
    t.column "reset_after",      :datetime
    t.column "promote_after",    :datetime
  end

  create_table "announcements", :force => true do |t|
    t.column "title",      :string
    t.column "user_id",    :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "body",       :text
    t.column "body_html",  :text
  end

  create_table "attributions", :force => true do |t|
    t.column "attributor_id",     :integer
    t.column "attributor_type",   :string
    t.column "attributable_id",   :integer
    t.column "attributable_type", :string
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
  end

  create_table "auto_tables", :force => true do |t|
    t.column "name",   :string
    t.column "schema", :text
  end

  create_table "blobs", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "local_name",       :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "title",            :string
    t.column "body",             :text
    t.column "body_html",        :text
    t.column "content_blob_id",  :integer
    t.column "content_type_id",  :integer
    t.column "license_id",       :integer
  end

  create_table "blog_posts", :force => true do |t|
    t.column "blog_id",    :integer
    t.column "title",      :string
    t.column "body",       :text
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "body_html",  :text
  end

  create_table "blogs", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "title",            :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "bookmarks", :force => true do |t|
    t.column "title",             :string,   :limit => 50, :default => ""
    t.column "created_at",        :datetime,                               :null => false
    t.column "bookmarkable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "bookmarkable_id",   :integer,                :default => 0,  :null => false
    t.column "user_id",           :integer,                :default => 0,  :null => false
  end

  add_index "bookmarks", ["user_id"], :name => "index_bookmarks_on_user_id"

  create_table "citations", :force => true do |t|
    t.column "user_id",          :integer
    t.column "workflow_id",      :integer
    t.column "workflow_version", :integer
    t.column "authors",          :text
    t.column "title",            :string
    t.column "publication",      :string
    t.column "published_at",     :datetime
    t.column "accessed_at",      :datetime
    t.column "url",              :string
    t.column "isbn",             :string
    t.column "issn",             :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "client_applications", :force => true do |t|
    t.column "name",         :string
    t.column "url",          :string
    t.column "support_url",  :string
    t.column "callback_url", :string
    t.column "key",          :string,   :limit => 50
    t.column "secret",       :string,   :limit => 50
    t.column "user_id",      :integer
    t.column "key_type",     :string
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
    t.column "creator_id",   :integer
  end

  add_index "client_applications", ["key"], :name => "index_client_applications_on_key", :unique => true

  create_table "comments", :force => true do |t|
    t.column "comment",          :text
    t.column "created_at",       :datetime,                               :null => false
    t.column "commentable_id",   :integer,                :default => 0,  :null => false
    t.column "commentable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",          :integer,                :default => 0,  :null => false
  end

  add_index "comments", ["user_id"], :name => "index_comments_on_user_id"

  create_table "content_blobs", :force => true do |t|
    t.column "data", :binary
  end

  create_table "content_types", :force => true do |t|
    t.column "user_id",          :integer
    t.column "title",            :string
    t.column "description",      :text
    t.column "description_html", :text
    t.column "mime_type",        :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "category",         :string
  end

  create_table "contributions", :force => true do |t|
    t.column "contributor_id",       :integer
    t.column "contributor_type",     :string
    t.column "contributable_id",     :integer
    t.column "contributable_type",   :string
    t.column "policy_id",            :integer
    t.column "created_at",           :datetime
    t.column "updated_at",           :datetime
    t.column "downloads_count",      :integer,  :default => 0
    t.column "viewings_count",       :integer,  :default => 0
    t.column "label",                :string
    t.column "rating",               :float
    t.column "license_id",           :integer
    t.column "rank",                 :float
    t.column "content_type_id",      :integer
    t.column "site_downloads_count", :integer,  :default => 0
    t.column "site_viewings_count",  :integer,  :default => 0
  end

  add_index "contributions", ["contributable_id", "contributable_type"], :name => "index_contributions_on_contributable_id_and_contributable_type"
  add_index "contributions", ["contributor_id", "contributor_type"], :name => "index_contributions_on_contributor_id_and_contributor_type"

  create_table "creditations", :force => true do |t|
    t.column "creditor_id",     :integer
    t.column "creditor_type",   :string
    t.column "creditable_id",   :integer
    t.column "creditable_type", :string
    t.column "created_at",      :datetime
    t.column "updated_at",      :datetime
  end

  create_table "curation_events", :force => true do |t|
    t.column "user_id",      :integer
    t.column "category",     :string
    t.column "object_type",  :string
    t.column "object_id",    :integer
    t.column "details",      :text
    t.column "details_html", :text
    t.column "created_at",   :datetime
    t.column "updated_at",   :datetime
  end

  create_table "downloads", :force => true do |t|
    t.column "contribution_id",    :integer
    t.column "user_id",            :integer
    t.column "created_at",         :datetime
    t.column "user_agent",         :string
    t.column "accessed_from_site", :boolean,  :default => false
  end

  add_index "downloads", ["contribution_id"], :name => "index_downloads_on_contribution_id"

  create_table "experiments", :force => true do |t|
    t.column "title",            :string
    t.column "description",      :text
    t.column "description_html", :text
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "friendships", :force => true do |t|
    t.column "user_id",     :integer
    t.column "friend_id",   :integer
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
    t.column "message",     :string,   :limit => 500
  end

  add_index "friendships", ["friend_id"], :name => "index_friendships_on_friend_id"
  add_index "friendships", ["user_id"], :name => "index_friendships_on_user_id"

  create_table "group_announcements", :force => true do |t|
    t.column "title",      :string
    t.column "network_id", :integer
    t.column "user_id",    :integer
    t.column "public",     :boolean,  :default => false
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
    t.column "body",       :text
    t.column "body_html",  :text
  end

  create_table "jobs", :force => true do |t|
    t.column "title",            :string
    t.column "description",      :text
    t.column "description_html", :text
    t.column "experiment_id",    :integer
    t.column "user_id",          :integer
    t.column "runnable_id",      :integer
    t.column "runnable_version", :integer
    t.column "runnable_type",    :string
    t.column "runner_id",        :integer
    t.column "runner_type",      :string
    t.column "submitted_at",     :datetime
    t.column "started_at",       :datetime
    t.column "completed_at",     :datetime
    t.column "last_status",      :string
    t.column "last_status_at",   :datetime
    t.column "job_uri",          :string
    t.column "job_manifest",     :binary
    t.column "inputs_uri",       :string
    t.column "inputs_data",      :binary
    t.column "outputs_uri",      :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "parent_job_id",    :integer
  end

  create_table "key_permissions", :force => true do |t|
    t.column "client_application_id", :integer
    t.column "for",                   :string
  end

  create_table "license_attributes", :force => true do |t|
    t.column "license_id",        :integer
    t.column "license_option_id", :integer
    t.column "created_at",        :datetime
  end

  create_table "license_options", :force => true do |t|
    t.column "user_id",          :integer
    t.column "title",            :string
    t.column "description",      :text
    t.column "description_html", :text
    t.column "uri",              :string
    t.column "predicate",        :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "licenses", :force => true do |t|
    t.column "user_id",          :integer
    t.column "unique_name",      :string
    t.column "title",            :string
    t.column "description",      :text
    t.column "description_html", :text
    t.column "url",              :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "memberships", :force => true do |t|
    t.column "user_id",                :integer
    t.column "network_id",             :integer
    t.column "created_at",             :datetime
    t.column "user_established_at",    :datetime
    t.column "network_established_at", :datetime
    t.column "message",                :string,   :limit => 500
    t.column "administrator",          :boolean,                 :default => false
  end

  add_index "memberships", ["network_id"], :name => "index_memberships_on_network_id"
  add_index "memberships", ["user_id"], :name => "index_memberships_on_user_id"

  create_table "messages", :force => true do |t|
    t.column "from",                 :integer
    t.column "to",                   :integer
    t.column "subject",              :string
    t.column "body",                 :text
    t.column "reply_id",             :integer
    t.column "created_at",           :datetime
    t.column "read_at",              :datetime
    t.column "body_html",            :text
    t.column "deleted_by_sender",    :boolean,  :default => false
    t.column "deleted_by_recipient", :boolean,  :default => false
  end

  create_table "networks", :force => true do |t|
    t.column "user_id",          :integer
    t.column "title",            :string
    t.column "unique_name",      :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "description",      :text
    t.column "description_html", :text
    t.column "auto_accept",      :boolean,  :default => false
  end

  add_index "networks", ["user_id"], :name => "index_networks_on_user_id"

  create_table "oauth_nonces", :force => true do |t|
    t.column "nonce",      :string
    t.column "timestamp",  :integer
    t.column "created_at", :datetime
    t.column "updated_at", :datetime
  end

  add_index "oauth_nonces", ["nonce", "timestamp"], :name => "index_oauth_nonces_on_nonce_and_timestamp", :unique => true

  create_table "oauth_tokens", :force => true do |t|
    t.column "user_id",               :integer
    t.column "type",                  :string,   :limit => 20
    t.column "client_application_id", :integer
    t.column "token",                 :string,   :limit => 50
    t.column "secret",                :string,   :limit => 50
    t.column "authorized_at",         :datetime
    t.column "invalidated_at",        :datetime
    t.column "created_at",            :datetime
    t.column "updated_at",            :datetime
  end

  add_index "oauth_tokens", ["token"], :name => "index_oauth_tokens_on_token", :unique => true

  create_table "pack_contributable_entries", :force => true do |t|
    t.column "pack_id",               :integer,  :null => false
    t.column "contributable_id",      :integer,  :null => false
    t.column "contributable_version", :integer
    t.column "contributable_type",    :string,   :null => false
    t.column "comment",               :text
    t.column "user_id",               :integer,  :null => false
    t.column "created_at",            :datetime
    t.column "updated_at",            :datetime
  end

  create_table "pack_remote_entries", :force => true do |t|
    t.column "pack_id",       :integer,  :null => false
    t.column "title",         :string,   :null => false
    t.column "uri",           :string,   :null => false
    t.column "alternate_uri", :string
    t.column "comment",       :text
    t.column "user_id",       :integer,  :null => false
    t.column "created_at",    :datetime
    t.column "updated_at",    :datetime
  end

  create_table "packs", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "title",            :string
    t.column "description",      :text
    t.column "description_html", :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "pending_invitations", :force => true do |t|
    t.column "email",        :string
    t.column "created_at",   :datetime
    t.column "request_type", :string
    t.column "requested_by", :integer
    t.column "request_for",  :integer
    t.column "message",      :string,   :limit => 500
    t.column "token",        :string
  end

  create_table "permissions", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "policy_id",        :integer
    t.column "download",         :boolean,  :default => false
    t.column "edit",             :boolean,  :default => false
    t.column "view",             :boolean,  :default => false
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  add_index "permissions", ["policy_id"], :name => "index_permissions_on_policy_id"

  create_table "picture_selections", :force => true do |t|
    t.column "user_id",    :integer
    t.column "picture_id", :integer
    t.column "created_at", :datetime
  end

  create_table "pictures", :force => true do |t|
    t.column "data",    :binary
    t.column "user_id", :integer
  end

  create_table "policies", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "name",             :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "share_mode",       :integer
    t.column "update_mode",      :integer
  end

  create_table "profiles", :force => true do |t|
    t.column "user_id",             :integer
    t.column "picture_id",          :integer
    t.column "email",               :string
    t.column "website",             :string
    t.column "created_at",          :datetime
    t.column "updated_at",          :datetime
    t.column "body",                :text
    t.column "body_html",           :text
    t.column "field_or_industry",   :string
    t.column "occupation_or_roles", :string
    t.column "organisations",       :text
    t.column "location_city",       :string
    t.column "location_country",    :string
    t.column "interests",           :text
    t.column "contact_details",     :text
  end

  add_index "profiles", ["user_id"], :name => "index_profiles_on_user_id"

  create_table "ratings", :force => true do |t|
    t.column "rating",        :integer,                :default => 0
    t.column "created_at",    :datetime,                               :null => false
    t.column "rateable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "rateable_id",   :integer,                :default => 0,  :null => false
    t.column "user_id",       :integer,                :default => 0,  :null => false
  end

  add_index "ratings", ["user_id"], :name => "index_ratings_on_user_id"

  create_table "relationships", :force => true do |t|
    t.column "network_id",  :integer
    t.column "relation_id", :integer
    t.column "created_at",  :datetime
    t.column "accepted_at", :datetime
  end

  create_table "remote_workflows", :force => true do |t|
    t.column "workflow_id",        :integer
    t.column "workflow_version",   :integer
    t.column "taverna_enactor_id", :integer
    t.column "workflow_uri",       :string
  end

  create_table "reviews", :force => true do |t|
    t.column "title",           :string,                 :default => ""
    t.column "review",          :text
    t.column "created_at",      :datetime,                               :null => false
    t.column "updated_at",      :datetime,                               :null => false
    t.column "reviewable_id",   :integer,                :default => 0,  :null => false
    t.column "reviewable_type", :string,   :limit => 15, :default => "", :null => false
    t.column "user_id",         :integer,                :default => 0,  :null => false
  end

  add_index "reviews", ["user_id"], :name => "index_reviews_on_user_id"

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"
  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "user_id",       :integer
    t.column "created_at",    :datetime
  end

  add_index "taggings", ["tag_id", "taggable_type"], :name => "index_taggings_on_tag_id_and_taggable_type"
  add_index "taggings", ["user_id", "tag_id", "taggable_type"], :name => "index_taggings_on_user_id_and_tag_id_and_taggable_type"
  add_index "taggings", ["taggable_id", "taggable_type"], :name => "index_taggings_on_taggable_id_and_taggable_type"
  add_index "taggings", ["user_id", "taggable_id", "taggable_type"], :name => "index_taggings_on_user_id_and_taggable_id_and_taggable_type"

  create_table "tags", :force => true do |t|
    t.column "name",             :string
    t.column "taggings_count",   :integer,  :default => 0, :null => false
    t.column "vocabulary_id",    :integer
    t.column "description",      :text
    t.column "description_html", :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  add_index "tags", ["name"], :name => "index_tags_on_name"
  add_index "tags", ["taggings_count"], :name => "index_tags_on_taggings_count"

  create_table "taverna_enactors", :force => true do |t|
    t.column "title",            :string
    t.column "description",      :text
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "url",              :string
    t.column "username",         :string
    t.column "crypted_password", :string
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "topic_feedback", :force => true do |t|
    t.column "topic_id",     :integer
    t.column "user_id",      :integer
    t.column "probability",  :float
    t.column "display_flag", :boolean
    t.column "score",        :integer
    t.column "submit_dt",    :date
  end

  create_table "topic_runs", :force => true do |t|
    t.column "description", :string
    t.column "runtime",     :datetime
  end

  create_table "topic_tag_map", :force => true do |t|
    t.column "topic_id",     :integer
    t.column "tag_id",       :integer
    t.column "probability",  :float
    t.column "display_flag", :boolean
  end

  create_table "topic_workflow_map", :force => true do |t|
    t.column "topic_id",     :integer
    t.column "workflow_id",  :integer
    t.column "probability",  :float
    t.column "display_flag", :boolean
  end

  create_table "topics", :force => true do |t|
    t.column "name",   :string
    t.column "run_id", :integer
  end

  create_table "users", :force => true do |t|
    t.column "openid_url",                :string
    t.column "name",                      :string
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "last_seen_at",              :datetime
    t.column "username",                  :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "downloads_count",           :integer,                :default => 0
    t.column "viewings_count",            :integer,                :default => 0
    t.column "email",                     :string
    t.column "unconfirmed_email",         :string
    t.column "email_confirmed_at",        :datetime
    t.column "activated_at",              :datetime
    t.column "receive_notifications",     :boolean,                :default => true
    t.column "reset_password_code",       :string
    t.column "reset_password_code_until", :datetime
  end

  create_table "viewings", :force => true do |t|
    t.column "contribution_id",    :integer
    t.column "user_id",            :integer
    t.column "created_at",         :datetime
    t.column "user_agent",         :string
    t.column "accessed_from_site", :boolean,  :default => false
  end

  add_index "viewings", ["contribution_id"], :name => "index_viewings_on_contribution_id"

  create_table "vocabularies", :force => true do |t|
    t.column "user_id",          :integer
    t.column "title",            :string
    t.column "description",      :text
    t.column "description_html", :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
  end

  create_table "workflow_versions", :force => true do |t|
    t.column "workflow_id",       :integer
    t.column "version",           :integer
    t.column "revision_comments", :text
    t.column "contributor_id",    :integer
    t.column "contributor_type",  :string
    t.column "image",             :string
    t.column "svg",               :string
    t.column "title",             :string
    t.column "unique_name",       :string
    t.column "body",              :text
    t.column "body_html",         :text
    t.column "created_at",        :datetime
    t.column "updated_at",        :datetime
    t.column "license",           :string,   :limit => 10, :default => "by-sa"
    t.column "content_blob_id",   :integer
    t.column "file_ext",          :string
    t.column "last_edited_by",    :string
    t.column "content_type_id",   :integer
  end

  add_index "workflow_versions", ["workflow_id"], :name => "index_workflow_versions_on_workflow_id"

  create_table "workflows", :force => true do |t|
    t.column "contributor_id",   :integer
    t.column "contributor_type", :string
    t.column "image",            :string
    t.column "svg",              :string
    t.column "title",            :string
    t.column "unique_name",      :string
    t.column "body",             :text
    t.column "body_html",        :text
    t.column "created_at",       :datetime
    t.column "updated_at",       :datetime
    t.column "current_version",  :integer
    t.column "content_blob_id",  :integer
    t.column "file_ext",         :string
    t.column "last_edited_by",   :string
    t.column "content_type_id",  :integer
    t.column "license_id",       :integer
  end

end
